services:
  service_a:
    build: ./service_a
    container_name: service_a
    ports:
      - "5000:5000"

  service_b:
    build: ./service_b
    container_name: service_b
    ports:
      - "5001:5001"
    depends_on:
      - service_a
