version: "3.9"

services:
  web:
    build: ./web
    container_name: web
    networks:
      - challenge_net
    restart: unless-stopped

  client:
    build: ./client
    container_name: cliete
    networks:
      - challenge_net
    depends_on:
      - web
    restart: unless-stopped

networks:
  challenge_net:
    name: Desafio 1
    driver: bridge
